[project]
name = "monitor"
version = "0.5.0"
description = "A system monitor that log anomalies on a linux machine and sends out email alerts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "commitizen>=4.16.2",
    "psutil>=7.2.2",
]

[dependency-groups]
dev = [
    "commitizen>=4.16.2",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.5.0"
version_files = ["pyproject.toml:version"]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"
