[project]
name = "monitor"
version = "1.1.0"
description = "A system monitor that log anomalies on a linux machine and sends out email alerts"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "commitizen>=4.16.2",
    "psutil>=7.2.2",
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.7",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "commitizen>=4.16.2",
    "pydocstyle>=6.3.0",
    "pyment>=0.3.3",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.1.0"
version_files = ["pyproject.toml:version"]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
monitor = "monitor.main:main"
monitor-daily-report = "monitor.daily_report:main"
monitor-boot-notification = "monitor.boot_notification:main"
monitor-bot = "monitor.bot.main:main"
